version: 2.1

commands:
  test-nodejs:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Test
          command: npm run test:ci
jobs:
  node-v10:
    docker:
      - image: node:10
    steps:
      - test-nodejs
  node-v12:
    docker:
      - image: node:12
    steps:
      - test-nodejs
  node-v13:
    docker:
      - image: node:13
    steps:
      - test-nodejs

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
